import Head from "next/head";
import ImageOne from "../components/ImageOne";

export default function Home() {
    return (
        <div>
            <Head>
                <title>PeakyPure | شرکت طراحی و توسعه نرم افزاری</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <ImageOne />
                <div className="flex justify-center items-center min-h-screen text-white">
                    Content goes here. Parallax height grows with content
                    height.
                </div>
            </div>
        </div>
    );
}
